config/routes.rb
Linetimes::Application.routes.draw do
  resources :places

  resources :waits

  get "waiting/index"

  resources :products

  root to: 'waiting#index', as: 'waiting'

end

app/models/wait.rb
class Wait < ActiveRecord::Base
  attr_accessible :location_id, :time
end

app/controllers/waits_controller.rb
class WaitsController < ApplicationController
  # GET /waits
  # GET /waits.json
  def index
    @waits = Wait.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @waits }
    end
  end

  # GET /waits/1
  # GET /waits/1.json
  def show
    @wait = Wait.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @wait }
    end
  end

  # GET /waits/new
  # GET /waits/new.json
  def new
    @wait = Wait.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @wait }
    end
  end

  # GET /waits/1/edit
  def edit
    @wait = Wait.find(params[:id])
  end

  # POST /waits
  # POST /waits.json
  def create
    @wait = Wait.new(params[:wait])

    respond_to do |format|
      if @wait.save
        format.html { redirect_to @wait, notice: 'Wait was successfully created.' }
        format.json { render json: @wait, status: :created, location: @wait }
      else
        format.html { render action: "new" }
        format.json { render json: @wait.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /waits/1
  # PUT /waits/1.json
  def update
    @wait = Wait.find(params[:id])

    respond_to do |format|
      if @wait.update_attributes(params[:wait])
        format.html { redirect_to @wait, notice: 'Wait was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @wait.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /waits/1
  # DELETE /waits/1.json
  def destroy
    @wait = Wait.find(params[:id])
    @wait.destroy

    respond_to do |format|
      format.html { redirect_to waits_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/waits_helper.rb
module WaitsHelper
end

app/views/waits/_form.html.erb
<%= form_for(@wait) do |f| %>
  <% if @wait.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@wait.errors.count, "error") %> prohibited this wait from being saved:</h2>

      <ul>
      <% @wait.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :time %><br />
    <%= f.datetime_select :time %>
  </div>
  <div class="field">
    <%= f.label :location_id %><br />
    <%= f.text_field :location_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/waits/edit.html.erb
<h1>Editing wait</h1>

<%= render 'form' %>

<%= link_to 'Show', @wait %> |
<%= link_to 'Back', waits_path %>

app/views/waits/index.html.erb
<h1>Listing waits</h1>

<table>
  <tr>
    <th>Time</th>
    <th>Location</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @waits.each do |wait| %>
  <tr>
    <td><%= wait.time %></td>
    <td><%= wait.location_id %></td>
    <td><%= link_to 'Show', wait %></td>
    <td><%= link_to 'Edit', edit_wait_path(wait) %></td>
    <td><%= link_to 'Destroy', wait, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Wait', new_wait_path %>

app/views/waits/new.html.erb
<h1>New wait</h1>

<%= render 'form' %>

<%= link_to 'Back', waits_path %>

app/views/waits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Time:</b>
  <%= @wait.time %>
</p>

<p>
  <b>Location:</b>
  <%= @wait.location_id %>
</p>


<%= link_to 'Edit', edit_wait_path(@wait) %> |
<%= link_to 'Back', waits_path %>